spring:
  r2dbc:
    #url: r2dbc:mysql://localhost:3306/arka?allowPublicKeyRetrieval=true&useSSL=false
    url: r2dbc:mysql://arka.c4pg2u66azll.us-east-1.rds.amazonaws.com:3306/arka?allowPublicKeyRetrieval=true&useSSL=false
    #username: root
    username: admin
    #password: admin2025
    password: adminDev2025
server:
  port: 8081
