spring:
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:arka.c4pg2u66azll.us-east-1.rds.amazonaws.com}:${DB_PORT:3306}/${DB_NAME:arka}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:adminDev2025}
  sql:
    init:
      mode: never

server:
  port: 8082

logging:
  level:
    org.springframework.r2dbc: DEBUG

