services:
  # ===============================
  # Microservicio de Reportes
  # ===============================
  inventario-ms:
    build: .
    container_name: reportes-ms
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # Variables de conexión a la base de datos
      DB_HOST: arka.c4pg2u66azll.us-east-1.rds.amazonaws.com   # ← Usa el endpoint RDS real
      DB_PORT: 3306
      DB_NAME: arka
      DB_USER: admin
      DB_PASSWORD: adminDev2025
    ports:
      - "8082:8082"  # 8082 en tu PC → 8082 dentro del contenedor
    networks:
      - reportes-network



# ===============================
# Redes y Volúmenes
# ===============================
networks:
  reportes-network:
    driver: bridge

volumes:
  mysql_data:
