services:
  # ===============================
  # Microservicio de Carrito
  # ===============================
  carrito-ms:
    build: .
    container_name: carrito-ms
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # Variables de conexión a la base de datos
      DB_HOST: arka.c4pg2u66azll.us-east-1.rds.amazonaws.com   # ← Usa el endpoint RDS real
      DB_PORT: 3306
      DB_NAME: arka
      DB_USER: admin
      DB_PASSWORD: adminDev2025
    ports:
      - "8080:8080"  # 8080 en tu PC → 8080 dentro del contenedor
    networks:
      - carrito-network



# ===============================
# Redes y Volúmenes
# ===============================
networks:
  carrito-network:
    driver: bridge

volumes:
  mysql_data:
